default: &default
  adapter: postgresql
  encoding: unicode
  host: db_dev
  username: postgres
  password: password
  port: 5432

development:
  <<: *default
  database: kitchen_car_app_development

test:
  <<: *default
  database: kitchen_car_app_test

production:
  <<: *default
  database: kitchen_car_app_production
  username: kitchen_car_app
  password: <%= ENV["KITCHEN_CAR_APP_DATABASE_PASSWORD"] %>
